name: Build and deploy backend app to Azure

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and zip backend app
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'


      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          # npm run test --if-present


      - name: npm run test
        run: npm run test

      - name: Create deployment directory
        run: |
          mkdir deploy
          cp -r dist deploy
          cp package.json deploy
          cp package-lock.json deploy


      - name: Zip artifact for deployment
        run: |
          cd deploy
          zip -r ../data-api-release.zip .

      - name: Upload data-api artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: data-api
          path: data-api-release.zip

  deploy-data-api:
    runs-on: ubuntu-latest
    name: Deploy NestJs backend
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: data-api

      - name: Change directory to artifact location
        run: |
          ls -la
          unzip data-api-release.zip
          ls -la
          cd ./

      - name: Install dependencies
        run: npm ci # Use npm ci for lock file

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'care-manager-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NESTJS_PUBLISH_PROFILE }}
          package: ./ # Use current directory. the deploy action should unzip as well.