name: CI/CD - Deploy to Azure Web App

on:
  push:
    branches:
      - production # Triggered on pushes to the production branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: 'care-manager-api'
      AZURE_RESOURCE_GROUP: 'care_manager'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build NestJS app
        run: npm run build

      - name: Zip Artifacts
        run: |
          cd dist
          zip -r ../release.zip *

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ care-manager-api }}
          package: release.zip
          publish-profile: ${{ secrets.NESTJS_PUBLISH_PROFILE }}
