name: Build and deploy backend app to Azure

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and zip backend app
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present
          # npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          cd dist # Navigate to the dist directory
          zip -r data-api-release.zip ./* # zip everything in current directory
          pwd # debugging
          ls -l # debugging
      - name: Check if the zip file exists
        run: |
          ls -l dist/data-api-release.zip # Verify the zip file

      - name: Upload data-api artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: data-api
          path: dist/data-api-release.zip # Correct path
  deploy-data-api:
    runs-on: ubuntu-latest
    name: Deploy NestJs backend
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: data-api

      - name: Unzip artifact for deployment
        run: |
          unzip data-api.zip
          ls -l

      - name: Install dependencies
        run: |
          cd dist # Navigate to the unzipped directory
          npm install
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'care-manager-api'  # Your Azure app name
          slot-name: 'Production'
          publish-profile: ${{ secrets.NESTJS_PUBLISH_PROFILE }}  # Secret containing the publish profile
          package: dist # Deploy the dist folder