name: Build and deploy backend app to Azure

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and zip backend app
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          cd ${GITHUB_WORKSPACE}  # Ensure we're in the root of the backend project
          npm install
          npm run build --if-present
          # npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          cd ${GITHUB_WORKSPACE}/dist  # Ensure you're in the dist folder for zipping
          zip -r ${GITHUB_WORKSPACE}/data-api-release.zip ./*

      - name: Check if the zip file exists
        run: |
          ls -l ${GITHUB_WORKSPACE}/data-api-release.zip  # Check if the zip file exists before upload

      - name: Upload data-api artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: data-api
          path: ${GITHUB_WORKSPACE}/data-api-release.zip

  deploy-data-api:
    runs-on: ubuntu-latest
    name: Deploy NestJs backend
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: data-api

      - name: Unzip artifact for deployment
        run: unzip data-api-release.zip

      - name: Install dependencies
        run: |
          cd care_manager-api  # Ensure we're in the correct directory for npm install
          npm install

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'care-manager-api'  # Your Azure app name
          slot-name: 'Production'
          publish-profile: ${{ secrets.NESTJS_PUBLISH_PROFILE }}  # Secret containing the publish profile
          package: ${GITHUB_WORKSPACE}/dist  # Use the 'dist' folder for deployment
