name: Build and deploy backend app to Azure

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and zip backend app
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build
          # npm run test --if-present
          

      - name: Zip artifact for deployment
        run: |
          cd dist/src
          zip -r ../data-api-release.zip *
      

      - name: Upload data-api artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: data-api
          path: data-api-release.zip

  deploy-data-api:
    runs-on: ubuntu-latest
    name: Deploy NestJs backend
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: data-api

      - name: Unzip artifact for deployment
        run: unzip data-api-release.zip


      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'care-manager-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NESTJS_PUBLISH_PROFILE }}
          package: .
